apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapp
  labels:
    app: weatherapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: weatherapp
  template:
    metadata:
      labels:
        app: weatherapp
    spec:
      containers:
      - image: evgenyniko/weather_app:latest
        name: weatherapp
        ports:
        - containerPort: 8000
