apiVersion: v1
kind: Service
metadata:
  name: weatherapp-service
spec:
  type: NodePort
  selector:
    app: weatherapp
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
